"""Service command smoke tests for PowerShell entry point."""

from .command_assertions import (
    assert_command_json_result,
    assert_command_json_error,
    assert_workspace_seed_json_result,
    assert_preflight_ai_reason_blocked_json_error,
)
from .service_assertions import (
    assert_service_retry_json_result,
    assert_service_resume_json_result,
    assert_service_run_json_result,
    assert_service_reconcile_json_result,
    assert_service_recover_json_result,
)


PYTHON = "python"


def append_root_ps1_service_retry_errors(errors: list[str]) -> None:
    root_ps1 = [
        "powershell.exe",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        "safeclaw.ps1",
    ]
    result = assert_command_json_result(
        [
            PYTHON,
            "tools/mvp/safeclaw_mvp.py",
            "seed-failed",
            "--reset",
            "--task-id",
            "task-readme-root-failed-ps1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-retry-seed-failed-json",
        "seed-failed",
    )
    assert_workspace_seed_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-retry-seed-failed-json",
        expected_action="seed-failed",
        expected_task_id="task-readme-root-failed-ps1",
    )
    assert_preflight_ai_reason_blocked_json_error(
        [
            *root_ps1,
            "service-retry",
            "--task-id",
            "task-readme-root-failed-ps1",
            "--limit",
            "1",
            "--report",
            "--preflight",
            "--preflight-action",
            "ai-reason",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-retry-preflight-ai-json",
        "service-retry",
    )
    result = assert_command_json_result(
        [
            *root_ps1,
            "service-retry",
            "--task-id",
            "task-readme-root-failed-ps1",
            "--limit",
            "1",
            "--report",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-retry-json",
        "service-retry",
    )
    assert_service_retry_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-retry-json",
        expected_db="target/mvp/workspaces/readme-root/session.db",
        expected_db_source="session",
        expected_task_id="task-readme-root-failed-ps1",
        expected_limit=1,
        expected_steps=["retry", "service-status", "report"],
        expect_report_payload=True,
    )


def append_root_ps1_service_resume_errors(errors: list[str]) -> None:
    root_ps1 = [
        "powershell.exe",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        "safeclaw.ps1",
    ]
    result = assert_command_json_result(
        [
            PYTHON,
            "tools/mvp/safeclaw_mvp.py",
            "seed-failed",
            "--reset",
            "--task-id",
            "task-readme-root-failed-resume-ps1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-not-hibernated-seed-failed-json",
        "seed-failed",
    )
    assert_workspace_seed_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-resume-not-hibernated-seed-failed-json",
        expected_action="seed-failed",
        expected_task_id="task-readme-root-failed-resume-ps1",
    )
    assert_command_json_error(
        [
            *root_ps1,
            "service-resume",
            "--task-id",
            "task-readme-root-failed-resume-ps1",
            "--limit",
            "1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-not-hibernated-json",
        "service-resume",
        expected_exit=1,
        expected_error_message_substring="failed step=resume",
        expected_top_level_error_code="resume-target-not-hibernated",
        expected_top_level_error_reason="resume_target_not_hibernated",
        expected_failed_step="resume",
        expected_code="resume-target-not-hibernated",
        expected_details_message_substring="resume only works for hibernated tasks",
    )
    result = assert_command_json_result(
        [
            *root_ps1,
            "service-run",
            "--reset",
            "--task-id",
            "task-readme-root-missing-resume-ps1",
            "--limit",
            "1",
            "--report",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-missing-service-run-json",
        "service-run",
    )
    assert_service_run_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-resume-missing-service-run-json",
        expected_db="target/mvp/workspaces/readme-root/session.db",
        expected_db_source="session",
        expected_task_id="task-readme-root-missing-resume-ps1",
        expected_limit=1,
        expected_steps=["run", "service-status", "report"],
        expect_report_payload=True,
        expected_run_db_source="workspace",
    )
    assert_command_json_error(
        [
            *root_ps1,
            "service-resume",
            "--task-id",
            "task-readme-root-missing-resume-ps1",
            "--limit",
            "1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-missing-json",
        "service-resume",
        expected_exit=1,
        expected_error_message_substring="failed step=resume",
        expected_top_level_error_code="resume-target-missing",
        expected_top_level_error_reason="hibernated_runtime_missing",
        expected_failed_step="resume",
        expected_code="resume-target-missing",
        expected_details_message_substring="resume requires a hibernated runtime for the selected task",
    )
    result = assert_command_json_result(
        [
            PYTHON,
            "tools/mvp/safeclaw_mvp.py",
            "seed-hibernated",
            "--reset",
            "--task-id",
            "task-readme-root-hibernated-ps1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-seed-hibernated-json",
        "seed-hibernated",
    )
    assert_workspace_seed_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-resume-seed-hibernated-json",
        expected_action="seed-hibernated",
        expected_task_id="task-readme-root-hibernated-ps1",
    )
    assert_preflight_ai_reason_blocked_json_error(
        [
            *root_ps1,
            "service-resume",
            "--task-id",
            "task-readme-root-hibernated-ps1",
            "--limit",
            "1",
            "--report",
            "--preflight",
            "--preflight-action",
            "ai-reason",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-preflight-ai-json",
        "service-resume",
    )
    result = assert_command_json_result(
        [
            *root_ps1,
            "service-resume",
            "--task-id",
            "task-readme-root-hibernated-ps1",
            "--limit",
            "1",
            "--report",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-resume-json",
        "service-resume",
    )
    assert_service_resume_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-resume-json",
        expected_db="target/mvp/workspaces/readme-root/session.db",
        expected_db_source="session",
        expected_task_id="task-readme-root-hibernated-ps1",
        expected_limit=1,
        expected_steps=["resume", "service-status", "report"],
        expect_report_payload=True,
    )
def append_root_ps1_service_reconcile_errors(errors: list[str]) -> None:
    root_ps1 = [
        "powershell.exe",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        "safeclaw.ps1",
    ]
    result = assert_command_json_result(
        [
            PYTHON,
            "tools/mvp/safeclaw_mvp.py",
            "seed-crash",
            "--reset",
            "--probe-mode",
            "none",
            "--task-id",
            "task-readme-root-assumed-ps1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-reconcile-seed-crash-json",
        "seed-crash",
    )
    assert_workspace_seed_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-reconcile-seed-crash-json",
        expected_action="seed-crash",
        expected_task_id="task-readme-root-assumed-ps1",
    )
    assert_preflight_ai_reason_blocked_json_error(
        [
            *root_ps1,
            "service-reconcile",
            "--task-id",
            "task-readme-root-assumed-ps1",
            "--decision",
            "executed",
            "--limit",
            "1",
            "--report",
            "--preflight",
            "--preflight-action",
            "ai-reason",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-reconcile-preflight-ai-json",
        "service-reconcile",
    )
    result = assert_command_json_result(
        [
            *root_ps1,
            "service-reconcile",
            "--task-id",
            "task-readme-root-assumed-ps1",
            "--decision",
            "executed",
            "--limit",
            "1",
            "--report",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-reconcile-json",
        "service-reconcile",
    )
    assert_service_reconcile_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-reconcile-json",
        expected_db="target/mvp/workspaces/readme-root/session.db",
        expected_db_source="session",
        expected_task_id="task-readme-root-assumed-ps1",
        expected_limit=1,
        expected_decision="executed",
        expected_steps=["reconcile", "service-status", "report"],
        expect_report_payload=True,
    )

def append_root_ps1_service_recover_errors(errors: list[str]) -> None:
    root_ps1 = [
        "powershell.exe",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        "safeclaw.ps1",
    ]
    result = assert_command_json_result(
        [
            PYTHON,
            "tools/mvp/safeclaw_mvp.py",
            "seed-crash",
            "--reset",
            "--task-id",
            "task-readme-root-uncertain-ps1",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-recover-seed-crash-json",
        "seed-crash",
    )
    assert_workspace_seed_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-recover-seed-crash-json",
        expected_action="seed-crash",
        expected_task_id="task-readme-root-uncertain-ps1",
    )
    assert_preflight_ai_reason_blocked_json_error(
        [
            *root_ps1,
            "service-recover",
            "--task-id",
            "task-readme-root-uncertain-ps1",
            "--limit",
            "1",
            "--report",
            "--preflight",
            "--preflight-action",
            "ai-reason",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-recover-preflight-ai-json",
        "service-recover",
    )
    result = assert_command_json_result(
        [
            *root_ps1,
            "service-recover",
            "--task-id",
            "task-readme-root-uncertain-ps1",
            "--limit",
            "1",
            "--report",
            "--json",
        ],
        errors,
        "safeclaw-root-ps1-service-recover-json",
        "service-recover",
    )
    assert_service_recover_json_result(
        result,
        errors,
        "safeclaw-root-ps1-service-recover-json",
        expected_db="target/mvp/workspaces/readme-root/session.db",
        expected_db_source="session",
        expected_task_id="task-readme-root-uncertain-ps1",
        expected_limit=1,
        expected_steps=["recover", "service-status", "report"],
        expect_report_payload=True,
    )

